version: '3.6'

services:
  navidrome:
    container_name: "navidrome"
    image: navidrome-local:latest
    restart: unless-stopped
    ports:
      - "4633:4633"
    volumes:
      - /home/gagan/development/data:/data
      - /home/gagan/development/kirtans:/music:ro
      - /home/gagan/development/japtapsamagams/logs:/logs
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: 4633
      ND_LOGFILE: /logs/log.txt
      ND_FFMPEGPATH: /usr/bin/ffmpeg
      ND_REVERSEPROXYWHITELIST: "0.0.0.0/0,::/0"
