version: '3.6'

services:
  navidrome:
    container_name: "navidrome"
    image: navidrome-local:latest
    restart: unless-stopped
    read_only: true
    ports:
      - "4633:4633"
    volumes:
      - /home/gagan/japtapsamagams/navidrome/data:/data
      - /home/gagan/music-dev:/music:ro
      - /home/gagan/japtapsamagams/logs:/logs
    environment:
      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data
      ND_PORT: 4633
      ND_LOGFILE: /logs/log.txt
      ND_FFMPEGPATH: /usr/bin/ffmpeg
